CREATE TABLE Fornecedor (
  CodForn INT PRIMARY KEY AUTO_INCREMENT,
  CPNJ VARCHAR(14) NOT NULL,
  Endereco VARCHAR (100),
  Contato INT
);

CREATE TABLE Lote (
  CodLT INT PRIMARY KEY AUTO_INCREMENT,
  DataFab DATE NOT NULL,
  DataVal DATE NOT NULL,
  CodForn INT NOT NULL, 
  FOREIGN KEY (CodForn) REFERENCES Fornecedor(CodForn)
);

CREATE TABLE Cidade (
  Nome VARCHAR (30) PRIMARY KEY,
  SiglaUF VARCHAR (2) NOT NULL
);

CREATE TABLE Filial (
  CodFilial INT PRIMARY KEY AUTO_INCREMENT,
  Endereco VARCHAR(100) NOT NULL,
  Cidade VARCHAR(30) NOT NULL, 
  FOREIGN KEY (Cidade) REFERENCES Cidade(Nome)
);

CREATE TABLE Empregado (
  CodEmp INT PRIMARY KEY AUTO_INCREMENT,
  Nome VARCHAR(50) NOT NULL,
  CPF INT NOT NULL,
  Endereco VARCHAR (100) NOT NULL,
  Contato INT NOT NULL,
  CodFilial INT NOT NULL, FOREIGN KEY (CodFilial) REFERENCES Filial(CodFilial)
);

CREATE TABLe Cliente(
  CodCliente INT PRIMARY KEY,
  Nome VARCHAR(50) NOT NULL,
  Contato INT NOT NULL,
  CPF INT,
  CPNJ VARCHAR(14)
); 

CREATE TABLE Venda (
  CodNF INT PRIMARY KEY,
  DataVenda DATE NOT NULL,
  Hora TIME NOT NULL,
  NrItens INT,
  CodCliente INT NOT NULL, FOREIGN KEY (CodCliente) REFERENCES Cliente(CodCLiente),
  CodFilial INT NOT NULL, FOREIGN KEY (CodFilial) REFERENCES Filial(CodFilial)
);

CREATE TABLE Produto (
  CodProd INT PRIMARY KEY, 
  Preco DECIMAL(10, 2) NOT NULL,
  CodLT INT NOT NULL, FOREIGN KEY (CodLT) REFERENCES Lote(CodLT),
  CodNF INT, FOREIGN KEY (CodNF) REFERENCES Venda(CodNF)
);
